### ISSUE TITLE
TSQL conditions raise error on empty values

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydelphin#262]
Executing a TSQL ~~regex-match~~ condition on a column with empty values can raise an error as these values are cast to `None`:

```console
$ delphin select 'i-id where error ~ "lexical gap"' mrs/
Traceback (most recent call last):
[...]
  File "/home/mwg/repos/pydelphin/delphin/tsql.py", line 422, in func
    return re.search(body[1], value)
  File "/usr/local/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

The problem is that `value` (in `tsql.py`) is `None`. A similar error occurs when the query's datatype doesn't match the column's datatype (see #261) but this problem with `None` also occurs even when they do match.

**Edit:** changed the title and text because it occurs with other operators and datatypes (e.g, doing an inequality comparison on a missing `:date` value).

**Comment by goodmami** [comment]
Note that this behavior may be affected by #258, e.g., if the meaning of `tsdb.cast()` changes.
