### ISSUE TITLE
User friendly error messages for commands

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydelphin#276]
For errors that occur when calling commands, the practice so far was to do nothing so the error that bubbles up shows the source and original cause of the error, which can be useful in debugging. This is less useful for users who make simple mistakes, such as giving a wrong path.

At least for the commands, it would probably be better to do a `sys.exit()` with an easy to understand message. For example, the following (current behavior) does specify the actual error, but it isn't very friendly:

```console
$ delphin process -g missing.dat mrs/
missing.dat: No such file or directory
Traceback (most recent call last):
  File "/home/mwg/repos/pydelphin/py36/bin/delphin", line 11, in <module>
    load_entry_point('PyDelphin', 'console_scripts', 'delphin')()
  File "/home/mwg/repos/pydelphin/delphin/main.py", line 40, in main
    args.func(args)
  File "/home/mwg/repos/pydelphin/delphin/cli/process.py", line 46, in call_process
    gzip=args.gzip)
  File "/home/mwg/repos/pydelphin/delphin/commands.py", line 613, in process
    with processor(grammar, cmdargs=options, **kwargs) as cpu:
  File "/home/mwg/repos/pydelphin/delphin/ace.py", line 110, in __init__
    self._open()
  File "/home/mwg/repos/pydelphin/delphin/ace.py", line 143, in _open
    raise ACEProcessError('Process closed on startup; see <stderr>.')
delphin.ace.ACEProcessError: Process closed on startup; see <stderr>.
```

If ACE's stderr message is guaranteed to appear (unless redirected by the user), then simply suppressing the stack trace might be better. Although `missing.dat` should only be a file, not a directory, so maybe a custom message wouldn't be bad.

The following is even less useful:

```console
$ delphin process -g erg.dat missing/
Traceback (most recent call last):
  File "/home/mwg/repos/pydelphin/py36/bin/delphin", line 11, in <module>
    load_entry_point('PyDelphin', 'console_scripts', 'delphin')()
  File "/home/mwg/repos/pydelphin/delphin/main.py", line 40, in main
    args.func(args)
  File "/home/mwg/repos/pydelphin/delphin/cli/process.py", line 46, in call_process
    gzip=args.gzip)
  File "/home/mwg/repos/pydelphin/delphin/commands.py", line 604, in process
    target = itsdb.TestSuite(testsuite)
  File "/home/mwg/repos/pydelphin/delphin/itsdb.py", line 689, in __init__
    '*schema* argument is required for new test suites')
delphin.itsdb.ITSDBError: *schema* argument is required for new test suites
```

Something like the following would be better:

```console
$ delphin process -g erg.dat missing/
missing/ is not a TSDB database
```

These two examples are not exhaustive; there are probably more areas for improvement.

**Comment by goodmami** [comment]
I decided to capture any `PyDelphinException` in `delphin.main` (that is, for every command), and only print its message when exiting unless the logger is set to DEBUG, in which case the stacktrace is printed.

I also added some more testing to the commands to raise appropriate errors on bad conditions. Any non-`PyDelphinException` errors will show up as before, which indicate an actual bug or an expected error that should be a subtype of `PyDelphinException`. I know of one case currently: invalid options for ACE with the `--options` option of `delphin process` raise a `ValueError`.
