### ISSUE TITLE
generation causes an exception when processing a profile

### ISSUE THREAD

**Issue by arademaker** [delph-in/pydelphin#314]
After finishing the annotation of https://github.com/arademaker/sick-fftb, I am using pydelphin to create a new profile with the best analysis for each sentence. The ideia is to compare the golden analysis with the best analysis from ACE. But...

```
% python process.py
    9746 bytes	relations
    8764 bytes	item
       0 bytes	analysis
       0 bytes	phenomenon
       0 bytes	parameter
       0 bytes	set
       0 bytes	item-phenomenon
       0 bytes	item-set
       0 bytes	run
       0 bytes	parse
       0 bytes	result
       0 bytes	rule
       0 bytes	output
       0 bytes	edge
       0 bytes	tree
       0 bytes	decision
       0 bytes	preference
       0 bytes	update
       0 bytes	fold
       0 bytes	score
Assertion failed: (ty->name[0]=='"'), function type_to_string, file type.c, line 625.
Traceback (most recent call last):
  File "process.py", line 13, in <module>
    tgt_ts.process(cpu, source=src_ts)
  File "/Users/ar/venv/lib/python3.8/site-packages/delphin/itsdb.py", line 881, in process
    response = cpu.process_item(datum, keys=keys_dict)
  File "/Users/ar/venv/lib/python3.8/site-packages/delphin/ace.py", line 284, in process_item
    response = self.interact(datum)
  File "/Users/ar/venv/lib/python3.8/site-packages/delphin/ace.py", line 257, in interact
    self.send(validated)
  File "/Users/ar/venv/lib/python3.8/site-packages/delphin/ace.py", line 201, in send
    self._p.stdin.write((datum.rstrip() + '\n'))
ValueError: I/O operation on closed file.
```

the code is:

```python
from delphin import itsdb
from delphin import ace
from delphin import commands

src_path = 'golden'
tgt_path = 'p'

commands.mkprof(tgt_path, source=src_path)
src_ts = itsdb.TestSuite(src_path)
tgt_ts = itsdb.TestSuite(tgt_path)
with ace.ACEGenerator('erg.dat') as cpu:
    tgt_ts.process(cpu, source=src_ts)
```

but from the command line, it works fine: 

```
% delphin process -g erg.dat -o "-n 1" -s golden parsed
```

**Comment by goodmami** [comment]
Closing as invalid; it looks like nothing was amiss here.
